runtime: python312
automatic_scaling:
  max_instances: 1
handlers:
- url: /(robots.txt)$
  secure: always
  redirect_http_response_code: 307
  expiration: 1d
  http_headers:
    Cross-Origin-Resource-Policy: same-origin
    No-Vary-Search: params
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
    Vary: Accept-Encoding
    X-Content-Type-Options: nosniff
  static_files: public/\1
  upload: public/robots.txt$
- url: /(.*)$
  secure: always
  redirect_http_response_code: 307
  expiration: 1h
  http_headers:
    Cross-Origin-Resource-Policy: same-origin
    No-Vary-Search: params
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
    Vary: Accept-Encoding
    X-Content-Type-Options: nosniff
  static_files: public/\1
  upload: public/.well-known/.*
