runtime: python312
default_expiration: 1h
handlers:
  - url: .*
    static_files: www\0
    upload: www/.*
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
      Vary: Accept-Encoding
      X-Content-Type-Options: nosniff
    secure: always
    redirect_http_response_code: 307
